/*

 HOUSE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\Home PC\Documents\KC Programming\C\Game Boy Development\background_gbp\brick_ts.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define houseWidth 40
#define houseHeight 18
#define houseBank 0

extern unsigned char house[];

/* End of HOUSE.H */
